name: CI

on: [push]

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: buildkite/trigger-pipeline-action@v1.2.0
      env:
        BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.BUILDKITE_API_ACCESS_TOKEN }}
        PIPELINE: "feelpp/feelpp-docs"
        COMMIT: "HEAD"
        BRANCH: "master"
        MESSAGE: ":github: Triggered from a GitHub Action by Tutorial-Dev Project"
  build_examples:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Build Tutorial Dev
      run: |
        mkdir build && cd build
        CXX=clang++-9 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./install ..
        make -j3
        make install
    - name: Ctest
      run: |
        ctest
      working-directory: build/install
    - name: Package
      run: |
        make package
        mkdir artifact && cp feelpp-tutorial-dev*.tar.gz artifact
        ls -l artifact
        tar tzvf feelpp-tutorial-dev*.tar.gz
      working-directory: build
#    - name: Upload artifact
#      uses: actions/upload-artifact@v1.0.0
#      with:
#        # Artifact name
#        name: Tutorial Dev-${{ runner.os }} 
#        # Directory containing files to upload
#        path: build/install/
