name: CI

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Build Tutorial Dev
      run: |
        mkdir build && cd build
        CXX=clang++-9 cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./install ..
        make -j3
        make install
    - name: Ctest
      run: |
        ctest
      working-directory: build/install
    - name: Package
      run: |
        make package
        mkdir artifact && cp tutorial-dev*.tar.gz artifact
        ls -l artifact
        tar tzvf tutorial-dev*.tar.gz
      working-directory: build
#    - name: Upload artifact
#      uses: actions/upload-artifact@v1.0.0
#      with:
#        # Artifact name
#        name: Tutorial Dev-${{ runner.os }} 
#        # Directory containing files to upload
#        path: build/install/
